### ISSUE TITLE
Unable to modify the Firefox profile

### ISSUE THREAD

**Issue by tebeka** [tebeka/selenium#10]
I'd like to be able to modify the firefox profile being used in order to add some custom configuration to the browser behaviour but I'm having difficulty understanding how to do this.
Please could you add an example of how to go about this? Many thanks.

(Dave Dexter in bitbucket issue 10)

**Comment by gauntface** [comment]
I've just tried out this library and it's awesome, but just hit this as well, not sure what string is expected as input or how it's used, any advice?

Cheers,
Matt

**Comment by tebeka** [comment]
Thanks @gauntface for reporting. It's been a while but I'll have a look, will try to answer soon-ish.
If you find the answer in the meantime, please let me know and I'll add it to the documentation.

**Comment by tebeka** [comment]
@gauntface  According to the spec you can specify the profile in the `Capabilities`.
They have an example at https://w3c.github.io/webdriver/webdriver-spec.html#capabilities

Does this answer your questions?

**Comment by minusnine** [comment]
I just committed a way to set the Firefox profile easily. See:

https://godoc.org/github.com/tebeka/selenium/firefox#Capabilities.SetProfile

An example on how to use it is in the tests:

https://github.com/tebeka/selenium/blob/master/remote_test.go#L284
