### ISSUE TITLE
Set selenium jar path when using chromedriver

### ISSUE THREAD

**Issue by BenKnigge** [tebeka/selenium#107]
How do you go about setting the selenium jar path when creating a new NewChromeDriverService?

**Comment by minusnine** [comment]
ChromeDriver is executed directly when calling that function. Selenium is not used.

To use Selenium, call `selenium.NewSeleniumService` instead. I guess there should be a `selenium.ServiceOption` to provide the path for the `webdriver.chrome.driver` system property. The current workaround would be to ensure the `chromedriver` binary is in the PATH.

**Comment by arpitjindal97** [comment]
Refer to #103 to see a sample using chromium

**Comment by minusnine** [comment]
Support for running Chromedriver under Selenium was committed a while ago in e9b07d5. I'm adding a test for it in a7288ca6, which I hope to have committed into master soon.
