### ISSUE TITLE
selenium.ByXPATH is broken

### ISSUE THREAD

**Issue by tebeka** [tebeka/selenium#11]
Suppose we have a website like:

``` html
<div class="box">
  <div class="word">
    <a href="I_NEED_THIS_VALUE">foo</a>
  </div>
</div>
<div class="box">
...
</div>
<div class="box">
...
</div>
```

I scrape box elements like so:

``` go
    elements, err := wd.FindElements(selenium.ByClassName, "box")
    panicIf(err)

    for _, element := range elements {
        el, err := element.FindElement(selenium.ByXPATH, "//div[contains(@class,'word')]/a/@href")
}
```

I get the error that the element is invalid. If I try just //div[contains(@class,'word')]/a, I will always get the first element in box div, not the first element of element. What can I do now?

(furion in bitbucket issue 11)

**Comment by tebeka** [comment]
@tebeka replied:
Thanks for reporting!
The XPATH searches are done by the Selenium server, the client only reports the answer. I'm not an XPATH expert, maybe try asking at https://groups.google.com/forum/#!forum/selenium-users or in https://stackoverflow.com?

`furion` said:
Well, my issue is, shouldn't XPATH be run on `element` node and not DOM root in my case?

**Comment by minusnine** [comment]
I just tested this in Selenium 2.53.1 and Firefox 47. It correctly reports this error:

```
InvalidSelectorError: The result of the xpath expression "//div[contains(@class,'word')]/a/@href" is: [object Attr]. It should be an element. For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
```

The correct strategy is to get the anchor element by leaving off the last part of the XPath expression, and then using GetAttribute("href") on that element.

Amusingly, the original XPath expression works in Selenium 3 and the latest Firefox Nightly, but actions on the returned element (e.g. we.GetTag()) expectedly fail. I'll file a bug.

**Comment by minusnine** [comment]
I looked at a slightly different problem above, but in any case, this is indeed a problem with either Selenium 2 or Geckodriver+Firefox, or both.
