### ISSUE TITLE
Error with go test -test.run

### ISSUE THREAD

**Issue by Courouge** [tebeka/selenium#112]
`go test -test.run=Example github.com/tebeka/selenium`

> github.com/tebeka/selenium
> src\github.com\tebeka\selenium\remote_test.go:21:2: cannot find package "github.com/google/go-cmp/cmp" in any of:
>         C:\go-work\src\github.com\tebeka\selenium\vendor\github.com\google\go-cmp\cmp (vendor tree)
>         C:\Go\src\github.com\google\go-cmp\cmp (from $GOROOT)
>         C:\go-work\src\github.com\google\go-cmp\cmp (from $GOPATH)
> FAIL    github.com/tebeka/selenium [setup failed]

Missing dependency:
`go get -u github.com/google/go-cmp/cmp`

**Comment by minusnine** [comment]
Dependency management is better with Go 1.12.
