### ISSUE TITLE
Trying to get it working with docker selenium/standalone-chrome container

### ISSUE THREAD

**Issue by andy-miracl** [tebeka/selenium#115]
Hi, I have managed to successfully use this library with `selenium/standalone-firefox` docker container to drive some tests. It works great thanks!

However, I would like to do the same for firefox but I am getting this strange error :

```
Err: "unknown error - 33",
Message: "Unable to create new service: ChromeDriverService\n
Build info: version: '3.11.0', 
revision: 'e59cfb3', 
time: '2018-03-11T20:33:15.31Z'\n
System info: host: 'myhostname', 
ip: '127.0.1.1', 
os.name: 'Linux', 
os.arch: 'amd64', 
os.version: '4.13.0-38-generic', 
java.version: '1.8.0_151'\n
Driver info: driver.version: unknown",
```

Do I need to somehow connect a chromedriver binary or something. I am a little confused how to get this working. Can anyone help?

**Comment by andy-miracl** [comment]
Suddenly started working... not sure why.... will close this issue

**Comment by johnbalvin** [comment]
could you please share your docker file?
