### ISSUE TITLE
FindElement by LinkText is not working on non-latin text

### ISSUE THREAD

**Issue by tebeka** [tebeka/selenium#12]
I have a page like this:

``` html
<a href="">тест</a>
```

And code like

``` go
wd.FindElement(selenium.ByPartialLinkText, "тест")
```

will produce the no such element error. When using latin text everything is working as expected.

(Anonymous in bitbucket issue 12)

**Comment by tebeka** [comment]
Playing a bit with this example, the Selenium server return 500 on the get element request with a huge Java stack trace. Here's the relevant part (which IMO points to an encoding problem).

```
            "localizedMessage": "Unable to locate element: {\"method\":\"partial link text\",\"selector\":\"\u00d1\u0082\u00d0\u00b5\u00d1\u0081\u00d1\u0082\"}\nBuild info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'\nSystem info: host: 'archie.bunker', ip: '10.0.2.15', os.name: 'Linux', os.arch: 'amd64', os.version: '3.14.4-1-ARCH', java.version: '1.7.0_55'\nDriver info: driver.version: unknown",
```

**Comment by minusnine** [comment]
This was fixed at some point. I just committed a test that proves it.
