### ISSUE TITLE
如何截取浏览器图片？

### ISSUE THREAD

**Issue by esolo0121** [tebeka/selenium#133]
您好，我想截取浏览器的部分图片，思路是先把游览器全部截图，然后再通过元素坐标截取相应的图片，看了你的文档，但是没有找到相应的例子，只是找Screenshot()，是否能提供一个根据元素坐标截取图片的例子，谢谢。

**Comment by minusnine** [comment]
I'm sorry, but I can't read Chinese. Google Translate is surprisingly good on that text, though.

I don't know what you mean (or Google Translate means) by "intercepting images based on element coordinates" though.

Note that (*WebElement).Screenshot has just been merged. Maybe that can help?

**Comment by ego008** [comment]
Hi @minusnine , @esolo0121 means : 
How to take screenshots with coordinates? eg Screenshot(x1, y1, x2, y2).

**Comment by minusnine** [comment]
There is no direct way to do it. If it were me, I would probably create a div at exactly the coordinates I want, maybe by injecting one via (WebDriver).ExecuteScript, and getting that element via FindElement, and then using the new (WebElement).Screenshot method.

**Comment by Zereker** [comment]
老哥 你这样直接说中文,很不稳呀
