### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by crazcalm** [tebeka/selenium#136]
drivers: selenium-server-standalone-3.8.1.jar, geckodriver-v0.19.1-linux64, chromedriver-linux64-2.35

    marcus@marcus-ThinkPad-T430:~/gocode/src/github.com/tebeka/selenium$ go test -run ''
    map[alwaysMatch:map[moz:firefoxOptions:{ [] base64-encoded Firefox profile goes here <nil> map[]}]]--- FAIL: TestFirefoxSelenium3 (146.30s)
    --- FAIL: TestFirefoxSelenium3/Error (3.57s)
        remote_test.go:608: wd.FindElement(ByID, 'no-such-element'); err.HTTPCode = 404, want 500
        remote_test.go:611: wd.FindElement(ByID, 'no-such-element'); err.LegacyCode = 0, want 7
    --- FAIL: TestFirefoxSelenium3/ExtendedErrorMessage (0.16s)
        remote_test.go:634: Got error "invalid session id: No active session with ID ", expected error to start with "invalid session ID:"
    --- FAIL: TestFirefoxSelenium3/Capabilities (3.40s)
        remote_test.go:647: wd.Capabilities() returned error: unknown command: GET /session/96359c0d-3baf-45b1-bb37-8c8a01481302 did not match a known command
    --- FAIL: TestFirefoxSelenium3/AddCookie (3.55s)
        remote_test.go:1194: wd.GetCookies() returned diff (-want/+got):
            {*selenium.Cookie}.Path:
                -: "/"
                +: ""
    map[alwaysMatch:map[moz:firefoxOptions:{ [] base64-encoded Firefox profile goes here <nil> map[]}]]--- FAIL: TestFirefoxGeckoDriver (133.58s)
    --- FAIL: TestFirefoxGeckoDriver/Proxy (0.00s)
        remote_test.go:1674: wd.NewSession() returned error: invalid argument: httpProxyPort is not a valid proxy configuration capability
    --- FAIL: TestHTMLUnit (9.17s)
    --- FAIL: TestHTMLUnit/ExtendedErrorMessage (0.00s)
        remote_test.go:634: Got error "invalid session id: No active session with ID ", expected error to start with "invalid session ID:"
    FAIL
    exit status 1
    FAIL    github.com/tebeka/selenium      334.094s

**Comment by minusnine** [comment]
All the tests are now passing at HEAD.
