### ISSUE TITLE
Tag new versions

### ISSUE THREAD

**Issue by mbrt** [tebeka/selenium#145]
Many people (including me) use [dep](https://github.com/golang/dep) or similar tools to manage dependencies in their projects. The new [Go 1.11 modules feature](https://github.com/golang/go/wiki/Modules) also requires tagging packages using [SemVer](https://github.com/golang/go/wiki/Modules#semantic-import-versioning).

The last release of this repo is dated November 2016. Can you please tag your master branch periodically? We have no indication of how the APIs are changing and by default any dependency manager will pull the last tagged release (2 years old).

**Comment by inluxc** [comment]
I added to change mime to use the master branch.
By the way how is the project, is it still active, do you need any help with it?
