### ISSUE TITLE
有没有中国的小伙伴交流下

### ISSUE THREAD

**Issue by webxscan** [tebeka/selenium#147]
我QQ29295842     在用这个库的时候遇到挺多苦恼的

**Comment by minusnine** [comment]
Sorry, I don't personally read Chinese and no one has stepped up.

**Comment by Xuzan9396** [comment]
哈哈， 同问啊， 现在滑动解锁这个不知道咋弄

**Comment by qingzhuan** [comment]
遇到同样的问题了，问题解决了吗
