### ISSUE TITLE
remote.go undefined: Capabilities(49, 16)

### ISSUE THREAD

**Issue by linuxramu** [tebeka/selenium#155]
I am not able to get compile my UI tests since there is an error thrown 

failed to compile tested package: uialerts, reason: exit status 2, output: WORK=C:\Users\XXXXX\AppData\Local\Temp\go-build265136062
github.com/tebeka/selenium
..\..\..\github.com\tebeka\selenium\remote.go:49:16: undefined: Capabilities

Any help is appreciated

**Comment by minusnine** [comment]
The type `selenium.Capabilities` is located in the file `selenium.go` in the same directory as `remote.go`. It's unclear why it could not be found.
