### ISSUE TITLE
Error while downloading dependences

### ISSUE THREAD

**Issue by rogercoll** [tebeka/selenium#156]
When I run that command: `go get -d ./...`
I get this error on kali linux distro i86: `../../../../google.golang.org/api/transport/http/dial.go:30:2: no buildable Go source files in /root/go/src/google.golang.org/api/transport/http/internal/propagation

Anyone knows why is this happening?`

**Comment by inluxc** [comment]
Use dep for dependencies its better.

**Comment by minusnine** [comment]
This is not a bug for this package.

That said, Go 1.12 does a much better job managing dependencies now.
