### ISSUE TITLE
How to switch windows in case of multiple sessions

### ISSUE THREAD

**Issue by smile-chen95** [tebeka/selenium#158]
```go
sess1, _ := wd.NewSession()
sess2, _ := wd.NewSession()
wd.SwitchSession(sess1)
wd.Get("https://www.google.com/")
wd.SwitchSession(sess2)
wd.Get("https://www.facebook.com/")
wd.SwitchSession(sess1)
wd.Get("https://www.facebook.com/")
```
Such as this operation
After both sessions have accessed the web page, sess2 is started behind sess1, so in the window interface it is in front, then switch to sess1 to do some operations, but sess1 is still in the background, and does not put this sess1 window Wake up to the front desk
Am I getting it wrong? Can't wake up to the front desk?

**Comment by baogume** [comment]
```golang
s0 := wd.SessionID()
c0, _ := wd.CurrentWindowHandle()
s1, _ := wd.NewSession()
c1, _ := wd.CurrentWindowHandle()

wd.Get("https://www.sina.com")
wd.SwitchWindow(c0)
wd.SwitchSession(s0)
wd.Get("https://www.taobao.com")

wd.SwitchSession(s1)
wd.SwitchWindow(c1)
wd.Get("https://weibo.com")
```

This also has no switching focus...

**Comment by baogume** [comment]
After a lot of tests, I found that ```wd.Screenshot()``` can bring the chrome to the focus of the session, but using this to achieve the goal may not be very good. Is there any other way?

**Comment by Kur-Ich** [comment]
Thanks, this solved the issue for me as well. I was trying:

`wd.SwitchWindow(window)`

Adding wd.Screenshot() afterwards manages Chrome to focus.
