### ISSUE TITLE
Timestamp in log.Message get wrong timestamp

### ISSUE THREAD

**Issue by huhuyou2** [tebeka/selenium#160]
test remote_test.go, I found that timestamp in the console print like this:
`1970-01-19 08:22:19.898463 +0800 CST`  

And, actually `Timestamp` in response is 1556539898463(2019-04-29 19:15:09) when debug remote.go(Line1231).
And, I have  tried to take this 1556539898463 to time.Unix(0, int64(155653989846/1000)),  then I got  `1970-01-01 08:00:01.556539898 +0800 CST`

Is there some mistake of using time Lib? should we use time.Unix() like this time.Unix(int64(155653989846/1000), 0) in remote.go(Line 1231)?

Any help is appreciated

**Comment by minusnine** [comment]
Whoops. That's a bug; thanks for the report!

This is fixed at HEAD. Please re-open if it is not.
