### ISSUE TITLE
Several Weird Issues with the firefox driver

### ISSUE THREAD

**Issue by GrimTheReaper** [tebeka/selenium#177]
So, I randomly get this error, if the process takes ~4 seconds to do its thing: `Failed to decode response from marionette`, and then I also can't seem to rescale the resolution and its stuck on 720p. Any idea what might be causing these things?

**Comment by minusnine** [comment]
This isn't a problem with this package, but likely with Geckodriver:

https://github.com/mozilla/geckodriver/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22Failed+to+decode+response+from+marionette%22

Please contribute to one of those bugs or open a new one in that repository with debugging logs.
