### ISSUE TITLE
Adding Proxy support

### ISSUE THREAD

**Issue by rodzzlessa24** [tebeka/selenium#20]
Hey I'm trying to use proxies and I noticed there wasn't support for it yet. I could implement it if you want I was just wondering if there was anything specific of how you wanted implemented. 

Here is the selenium proxy manual
https://code.google.com/p/selenium/wiki/JsonWireProtocol#Proxy_JSON_Object

What I was thinking is just adding a simple Proxy struct

```
/* Proxy configuration. */
type Proxy struct {
	ProxyType          string `json:"proxyType"`
	ProxyAutoconfigURL string `json:"proxyAutoconfigUrl"`
	FTPProxy           string `json:"ftpProxy"`
	HTTPProxy          string `json:"httpProxy"`
	SSLProxy           string `json:"sslProxy"`
	SOCKSProxy         string `json:"socksProxy"`
	SOCKSUsername      string `json:"socksUsername"`
	SOCKSPassword      string `json:"socksPassword"`
	NoProxy            string `json:"noProxy"`
}
```

Then it can be passed in as an interface in capabilities. Something like:

```
caps := selenium.Capabilities{
"browserName": "firefox"
"proxy": selenium.Proxy
}
```

**Comment by tebeka** [comment]
Hi @rodzzlessa24, I'd appreciate a pull request. Super busy this week but will try to have a look soon-ish.

Thanks!

**Comment by rodzzlessa24** [comment]
I made a pull request and it just adds a simple proxy type:

`type Proxy [string]string`

and then to use it:

```
    proxy := selenium.Proxy{
		"proxyType":  "MANUAL",
		"socksProxy": "107.172.253.236:1080",
	}

	caps := selenium.Capabilities{
		"browserName": "firefox",
		"proxy":       proxy,
	}
	
	wd, _ := selenium.NewRemote(caps, "")
	defer wd.Quit()
```

It's not necessary to use the `Proxy` type but I think it just makes the API a little cleaner
