### ISSUE TITLE
Could not find or load main class org.openqa.grid.selenium.GridLauncherV3

### ISSUE THREAD

**Issue by pjstam** [tebeka/selenium#200]
Hello,
When trying the example in the example section I'm getting a 
Could not find or load main class org.openqa.grid.selenium.GridLauncherV3
when executing, Any ideas? Running a Windows system.
Regards,
Peter

**Comment by dikutandi** [comment]
have you fixed this issue?

**Comment by pjstam** [comment]
Yes, it was a wrong path issue....
