### ISSUE TITLE
WebDriverWait Supprt

### ISSUE THREAD

**Issue by rodzzlessa24** [tebeka/selenium#23]
Implementing Explicit and Implicit Wait API. I will look into this myself and submit a PR.

**Comment by viralkpanchal** [comment]
Hi,

I am trialing out this Selenium with Go. I would like to use WebDriverWait function to wait for an element to be visible / enabled.
For example, I can see this working with Java as mentioned here: https://www.seleniumhq.org/docs/04_webdriver_advanced.jsp

Is there a support for this with an example?

Regards,
VP
