### ISSUE TITLE
Timeout is not  valid.

### ISSUE THREAD

**Issue by mejinke** [tebeka/selenium#30]
```
caps := selenium.Capabilities{"browserName": "firefox"}
wd, _ := selenium.NewRemote(caps, "")
defer wd.Quit()
wd.SetPageLoadTimeout(5000) //5s
wd.Get("http://xxxxxx")
span, _ := wd.FindElement(selenium.ByCSSSelector, ".pd-name")
fmt.Println(span.Text())
```

".pd - name " loaded, I will stop page continues to load.But set the timeout seems to have no effect.

Help me.

Thank you.

**Comment by tebeka** [comment]
Thanks for reporting. I'll take a look soon-ish

**Comment by tebeka** [comment]
If you run the following code, you'll see that `5000` is `5us`. (see [here](https://play.golang.org/p/gZ6F3Vn4iH)). Is this what you intended?

```go
package main

import (
	"fmt"
	"time"
)

func printDuration(d time.Duration) {
	fmt.Println(d)
}

func main() {
	printDuration(5000)
}
```

**Comment by tebeka** [comment]
@mejinke Does the above solve your problem?
