### ISSUE TITLE
Scroll to element

### ISSUE THREAD

**Issue by eranchetz** [tebeka/selenium#31]
Hi, 

I was wondering how to put an element in view,

I assumed using _FindElement_ will scroll to the relevant element but using screenshot I see that won't work.

I also tried to use MoveTo(0,0) but it seems it's not scrolling as well.

What is the correct way to scroll to element?

Thanks,
@eranchetz

**Comment by eranchetz** [comment]
Looks like LocationInView will do that for me! 

Can someone please confirm?

thanks

**Comment by tebeka** [comment]
I don't think `LocationInView` will scroll. It's the location once the element will be in view (see [here](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelementidlocation_in_view)). 

See [this StackOverflow question](http://stackoverflow.com/questions/3401343/scroll-element-into-view-with-selenium) for ways on how to do this.

**Comment by eranchetz** [comment]
@tebeka Any idea how I import the Actions package in golang?

**Comment by tebeka** [comment]
You use the `ExecuteScript` method.

**Comment by eranchetz** [comment]
I think the answer is here : https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidmoveto

> ...If the element is not visible, it will be scrolled into view...

I think the solution is the use a combination of moveTo and LocationInView. 

I will try to add an example here

**Comment by tebeka** [comment]
Thanks @eranchetz ! Please close the issue when you do that.

**Comment by eranchetz** [comment]
Below is an example of how to scroll into view (and take a screenshot): 
```
...
wd, err := selenium.NewRemote(caps, "")
...
graph, _ := wd.FindElement(selenium.ByXPATH, `//*[@id="1"]/div[1]/div[3]/div[3]/div/div`)
	//Scroll to view without offset!
	graph.MoveTo(0, 0)
	for {
		isdisplayed, _ := graph.IsDisplayed()
		if isdisplayed {
			break
		} else {
			time.Sleep(time.Millisecond * 100)
		}
	}
       //Get actual location of graph element
        location, _ = graph.LocationInView()
	graphScrnShot, _ := wd.Screenshot()

	graphImg, _, _ := image.Decode(g2)
     ...

```

more reference here:
- https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidmoveto
- https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelementidlocation_in_view
