### ISSUE TITLE
Method SwitchFrame(frame string) should be implemented with a map[string]interface{}

### ISSUE THREAD

**Issue by exjimsk** [tebeka/selenium#33]
This would allow specification [8.5 Switch to Frame](https://w3c.github.io/webdriver/webdriver-spec.html#switch-to-frame) to be properly implemented as a null id value is required to switch to the default content.

**Comment by exjimsk** [comment]
Pull request submitted and approved.  

Passing a 0 length string argument to SwitchFrame(frame) is like calling a SwitchToParentFrame() method.

**Comment by tebeka** [comment]
Thanks for keeping me tidy :)
