### ISSUE TITLE
Do we have such: driver.switchTo().defaultContent();  

### ISSUE THREAD

**Issue by MikhailKlemin** [tebeka/selenium#42]
I just see no way to switch back to frame container in Go, once I did say `err = wd.SwitchFrame("middle")`, there no way I can switch back to page which holds all frames. 
Or there is?

**Comment by tebeka** [comment]
[According to StackOverflow](http://stackoverflow.com/questions/17856187/how-to-navigate-back-to-current-page-from-frame-in-selenium-webdriver) `wd.SwitchFrame("0")` should work.
