### ISSUE TITLE
Cannot set geckodriver in code

### ISSUE THREAD

**Issue by crantok** [tebeka/selenium#43]
I'm sure I had this working when I submitted that pull request to update the docs. I've just come back to it after many weeks and now I can't get it to work.

This **does** work:
```bash
java -Dwebdriver.gecko.driver="/home/me/Downloads/geckodriver" \
  -jar ~/Downloads/selenium-server-standalone-3.0.1.jar
```
with
```go
caps := selenium.Capabilities{
		"browserName":            "firefox",
}
```

This does **not** work:
```bash
java -jar ~/Downloads/selenium-server-standalone-3.0.1.jar
```
with
```go
caps := selenium.Capabilities{
		"browserName":            "firefox",
		"webdriver.gecko.driver": "/home/me/Downloads/geckodriver",
}
```
It gives error:
```
The path to the driver executable must be set by the webdriver.gecko.driver \
system property; for more information, see https://github.com/mozilla/geckodriver. \
The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
```

**Comment by tebeka** [comment]
Thanks for reporting. It's been a while sine I've used Selenium and not that familiar with Selenium 3 to solve this one. Maybe others can help? (@crantok?)

**Comment by crantok** [comment]
I think this issue and #41 may be related.

I enabled debug logging
```go
	selenium.SetDebug(true)
```
and added pretty printing of JSON responses (see my pull request #44) to make reading the logs easier.

I tried adding the proxy settings used in #41
```go
    proxy := selenium.Proxy{
        Type:  "manual",
        SOCKS: "107.172.253.236:1080",
    }

    caps := selenium.Capabilities{
        "browserName": "firefox",
        "proxy":       proxy,
    }
```
and that silently failed. The JSON response from creating a new session does not include the proxy settings, nor is any error reoprted:
```js
2016/11/18 15:12:30 <- 200 OK [[application/json; charset=utf-8]]
{
    "state": null,
    "sessionId": "b0e31871-eecf-4047-837d-ffce9f4fdadd",
    "hCode": 1405496451,
    "value": {
        "rotatable": false,
        "raisesAccessibilityExceptions": false,
        "firefoxOptions": {
            "args": [],
            "profile": "..."
        },
        "appBuildId": "20160920074044",
        "version": "49.0",
        "platform": "LINUX",

                             // <--- No Proxy Details!
        "proxy": {},         // <--- No Proxy Details!
                             // <--- No Proxy Details!

        "command_id": 1,
        "specificationLevel": 0,
        "acceptSslCerts": false,
        "processId": 18649,
        "webdriver.remote.sessionid": "b0e31871-eecf-4047-837d-ffce9f4fdadd",
        "browserVersion": "49.0",
        "platformVersion": "4.4.0-38-generic",
        "XULappId": "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}",
        "browserName": "firefox",
        "takesScreenshot": true,
        "takesElementScreenshot": true,
        "javascriptEnabled": true,
        "platformName": "linux",
        "device": "desktop",
        "cssSelectorsEnabled": true
    },
    "class": "org.openqa.selenium.remote.Response",
    "status": 0
}
```

Unfortunately, when I initialise the use of the geckodriver by passing its path directly to the selenium jar (see OP) I do not see "webdriver.gecko.driver" in the keys of the JSON response :-/

**Comment by DrMarcII** [comment]
Selenium Server does not support specifying the geckodriver exe location in capabilities. It must either be in a location pointed by the PATH or specified through the JVM system property webdriver.gecko.driver (e.g. by using java -Dwebdriver.gecko.driver=... --jar selenium-server-standalone.jar).

**Comment by minusnine** [comment]
@DrMarcII is correct, of course.

The above commit adds support for specifying the path to Geckodriver when using the provided Service type, which was recently added.
