### ISSUE TITLE
Pdeathsig cannot be used on Darwin

### ISSUE THREAD

**Issue by tinyshrimp** [tebeka/selenium#48]
The 'Pdeathsig' of SysProcAttr struct only can be used on Linux, it will make compiling failure on macOS.

The error message as following
```
./service.go:118: unknown syscall.SysProcAttr field 'Pdeathsig' in struct literal
./service.go:200: unknown syscall.SysProcAttr field 'Pdeathsig' in struct literal
```

Please see [SysProcAttr](https://golang.org/pkg/syscall/#SysProcAttr)

**Comment by minusnine** [comment]
Thank you for the bug report. I'll either work around this or add a build constraint later today.

**Comment by nagyzso94** [comment]
I have this exact same bug and can't find a solution. 😞
I get this error message: 
`unknown field 'Pdeathsig' in struct literal of type syscall.SysProcAttr`

**Comment by fangyufangxuan** [comment]
> I have this exact same bug and can't find a solution. 😞
> I get this error message:
> `unknown field 'Pdeathsig' in struct literal of type syscall.SysProcAttr`

service.go:	// TODO(minusnine): Pdeathsig is only supported on Linux. Somehow, make sure
