### ISSUE TITLE
Chrome Profile?

### ISSUE THREAD

**Issue by zero-master** [tebeka/selenium#5]
How can i start chrome with arguments ? or create a chrome profile?

**Comment by zhongguo168a** [comment]
How to use Firefox profile?

**Comment by tebeka** [comment]
Hi @zhongguo168a - this is currently not supported IIRC. It's been a while since I dealt with this package ...

**Comment by minusnine** [comment]
Whoops, I closed the wrong bug (even though this one went off to talk about _Firefox_ profiles). Chrome profiles are next.

**Comment by minusnine** [comment]
ChromeDriver doesn't permit setting the profile directly, but the [chrome.Capabilities](https://godoc.org/github.com/tebeka/selenium/chrome#Capabilities) type now allows you to set preferences, local state, and extentions (among others) directly.

**Comment by rosaCarolsampaio** [comment]
Has anyone been able to successfully set the Chrome profile?
