### ISSUE TITLE
Some more expamples for noobs.

### ISSUE THREAD

**Issue by SimplyDemon** [tebeka/selenium#57]
Hello Mr.Tebeka can u make some more exmples for understanding how it works. Ty anyway.

**Comment by minusnine** [comment]
Hi, the unit tests are the best place to see how to use the API.

https://github.com/tebeka/selenium/blob/master/remote_test.go

Also, the documentation for the API is here:

https://godoc.org/github.com/tebeka/selenium

Please let me know if you have any particular issues by opening another GitHub issue.
