### ISSUE TITLE
Proxy example, please?

### ISSUE THREAD

**Issue by MikhailKlemin** [tebeka/selenium#6]
Hello!
What is JSON Proxy Object and how to create it and supply to Capabilities? Can you throw a little example, say I have  proxy 
http://1.2.3.4:5678 

Sadly I lack any knowledge in JSON, I only Selenium to test some heavy Ajax content and I need to do it via proxies. 

EDIT: Reading JSON and GO and asking question on stackoverflow, seems like just need to use map[string]interface{} like
```go
caps := selenium.Capabilities{"browserName": "firefox", "proxy": map[string]interface{}{"proxyType": "manual", "httpProxy": "218.97.194.214:80"}}
```

**Comment by tebeka** [comment]
Hi,

It's been a while since I worked with Selenium. Sorry but I can't help you.
Probably ask in StackOverflow.

Good luck,
--
Miki

**Comment by MikhailKlemin** [comment]
Hi, you made great work, Mikki! Proxy works, as I added in edit.

**Comment by tebeka** [comment]
This is awesome! Happy testing ...
