### ISSUE TITLE
http headers

### ISSUE THREAD

**Issue by korjavin** [tebeka/selenium#81]
Is there a way to get http headers as well as PageSource ?

**Comment by minusnine** [comment]
PageSource is available via the aptly named [`PageSource` method](https://godoc.org/github.com/tebeka/selenium#WebDriver). 

I'm not aware of a way to get HTTP headers directly via the Web Driver API [1](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol) [2](https://www.w3.org/TR/webdriver/). You probably can write a small routine in Javascript and use the `ExecuteScript` method.

What header information are you interested in, though?

**Comment by korjavin** [comment]
Thank you!
I meant those header like wget shows
```
HTTP/1.1 200 OK^M
Server: nginx^M
Content-Type: text/html; charset=utf-8^M
X-Drupal-Cache: HIT^M
ETag: "1496940238.608-1"^M
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload^M
Content-Language: en^M
X-UA-Compatible: IE=edge,chrome=1^M
X-Generator: Drupal 7 (http://drupal.org)^M
Link: <https://www.whitehouse.gov/>; rel="canonical",<https://www.whitehouse.gov/>; rel="shortlink"^M
Last-Modified: Thu, 08 Jun 2017 16:43:58 GMT^M
X-Request-ID: v-f39a3534-4c69-11e7-839f-060579f87a72^M
X-AH-Environment: prod^M
X-Varnish: 231718458 231488195^M
X-Cache-Hits: 7^M
X-Age: 7^M
Vary: Accept-Encoding^M
Cache-Control: public, max-age=3415^M
Expires: Thu, 08 Jun 2017 17:46:44 GMT^M
Date: Thu, 08 Jun 2017 16:49:49 GMT^M
Transfer-Encoding:  chunked^M
Connection: keep-alive^M
Connection: Transfer-Encoding^M

```

**Comment by minusnine** [comment]
Right, so the headers between the browser and the server hosting the target page. Those headers aren't available in the WebDriver APIs. The best you could do, I think, is to use Javascript to perform a GET or HEAD on the same page and report it back via ExecuteScript, as I hinted at earlier.

**Comment by korjavin** [comment]
Thank you again! But what a pity ;(
