### ISSUE TITLE
SendModifier fails with "unknown command" error

### ISSUE THREAD

**Issue by We-St** [tebeka/selenium#82]
I'm trying to simulate keyboard events of the form **CTRL**+**key**, but get the following error when using `SendModifier`:

`unknown command: POST /session/<session-id>/modifier`

I can use `KeyDown` and `KeyUp` respectively, so I'm not really blocked by the issue. Also, it seems `SendModifier` is not adding any value to the library since `KeyDown` and `KeyUp` do the exact same?

**Comment by minusnine** [comment]
> unknown command: POST /session/<session-id>/modifier

This should be fixed as of last night when I merged b7708791b. Can you pull from this repository's head?

> Also, it seems SendModifier is not adding any value to the library since KeyDown and KeyUp do the exact same?

Yes. In fact, as of b7708791b, SendModifier is implemented using KeyDown and KeyUp. I just last night marked this function as deprecated.

https://godoc.org/github.com/tebeka/selenium

**Comment by minusnine** [comment]
Please feel free to re-open if this issue is not resolved. Thanks!
