### ISSUE TITLE
expose loggingPrefs api

### ISSUE THREAD

**Issue by jmhodges** [tebeka/selenium#86]
In order to get console logs from the WebDriver for Chrome, users have to type

```
caps := selenium.Capabilities{}
caps["loggingPrefs"] = map[string]string{"browser": "ALL"}
return selenium.NewRemote(caps, addr)
```

(That "ALL" is a filter level.)

It would be nice if this was wrapped in an explicit API. (Maybe I missed something in the current API though?)

**Comment by minusnine** [comment]
Thanks for the feedback!

Would the API provided in  the new [logging branch](https://github.com/tebeka/selenium/compare/topic/logging?expand=1) meet your needs?

Here are two example uses:

```go
var caps selenium.Capabilities
caps.SetLogLevel(log.Browser, log.All)
```

or

```go
var caps selenium.Capabilities
caps.AddLogging(log.Capabilities{
  log.Browser: log.All,
})
```

**Comment by jmhodges** [comment]
That's great. Thank you!

**Comment by minusnine** [comment]
I've merged this just now. Thanks again for the feature request. Please feel free to re-open this issue if something doesn't work as expected or can be improved.

**Comment by agnivade** [comment]
Sorry to comment on a dead thread. This is not working for me. I am unable to see any console output.

I have done this - 
```
caps.AddLogging(selLog.Capabilities{selLog.Browser: selLog.All})
```

And then
```
_, err = wd.ExecuteScript(`console.log("hi there")`, nil)
```

And this is what I see -
```
14:21:40.202 INFO - To upstream: {"args":[],"script":"console.log(\"hi there\")"}
14:21:40.223 INFO - To downstream: {"value":null}
2018/07/14 14:21:40 <- 200 OK [[application/json;charset=utf-8]]
{
    "value": null
}
```

What am I missing ?

**Comment by matthewmueller** [comment]
I also encountered this. I was able to start seeing logs with `selenium.Output`, basically the opposite that was suggested in: https://github.com/tebeka/selenium/issues/193.

This is quite noisy, so to reduce it down, you can do something like:

```go

type filterWriter struct {
	w io.Writer
}

func (f *filterWriter) Write(p []byte) (n int, err error) {
	if bytes.Contains(p, []byte("CONSOLE(")) {
		return f.w.Write(p)
	}
	return len(p), nil
}

var opts []selenium.ServiceOption
opts = append(opts, selenium.Output(&filterWriter{os.Stderr}))
service, err := selenium.NewChromeDriverService("chromedriver", 4444, opts...)
if err != nil {
	return nil, fmt.Errorf("error starting the ChromeDriver server: %w", err)
}
```
