### ISSUE TITLE
Unexpected Content Type from Selenium Server

### ISSUE THREAD

**Issue by beforeisleep** [tebeka/selenium#88]
I followed the instructions on https://godoc.org/github.com/tebeka/selenium and ran the example code. Unfortunately, I get the following error on selenium.NewRemote():

--- FAIL: Test_Selenium (0.15s)
panic: got content type "text/html", expected "application/json" [recovered]
	panic: got content type "text/html", expected "application/json"

I am running selenium-server-standalone-3.4.0. Any help to resolve this would be much appreciated.

**Comment by minusnine** [comment]
You may need to pass a different `urlPrefix` to the `NewRemote` function.

If that doesn't work, will you add a call `selenium.SetDebug(true)` before the call to `NewRemote`, and provide the log?

**Comment by minusnine** [comment]
I just committed a more explicit example that might help you understand how to use the API and/or what went wrong. Please see the example near the top of:

https://godoc.org/github.com/tebeka/selenium

If you still have issues, you can modify the example as described there, obtain the output that is produced, and please re-open this issue with it included.
