### ISSUE TITLE
Is there any way to make browser wait for the condition to be true?

### ISSUE THREAD

**Issue by serge1peshcoff** [tebeka/selenium#89]
In selenium-webdriver bindings there are methods for browser to wait till condition would evaluate to true, for example, in Node.js

    let el = driver.findElement(By.id(`some-id`));
    driver.wait(until.elementIsVisible(el),100); // wait for element to be visible

Is there any method to do the same thing in this library?

**Comment by the1337guy** [comment]
Doesn't it poll for it, try to look at the code, if it polls, then it's unscalable, and should not be used.

**Comment by serge1peshcoff** [comment]
@the1337guy what do you mean?

**Comment by minusnine** [comment]
I think this is a duplicate of #62. Please read the discussion there and feel free to comment and make suggestions.

**Comment by serge1peshcoff** [comment]
@minusnine most likely, yeah, that's what I was looking for. Closing this issue then.
