### ISSUE TITLE
Improve ByID and ByName speed of  FindElement

### ISSUE THREAD

**Issue by dlintw** [tebeka/selenium#92]
I found the source code of  FindElement ByID and ByName is just call css selector.
Is there any method to speed up? (I use chromedrive)

**Comment by minusnine** [comment]
This package just wraps the API provided by ChromeDriver, Geckodriver, or WebDriver. The call from this package to the "server" that implements the actual logic is a simple POST request.

https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelement
https://www.w3.org/TR/webdriver/#find-element

The newer versions of those components implement the second API. That specification removed the special cases for searching by ID and name in favor of using the more generic CSS selector strategy.

If you have performance issues with ChromeDriver, you should file a bug with performance data (e.g. benchmark results) and specific expectations with them.
