### ISSUE TITLE
elem.GetAttribute("innerHTML") does not seems like works

### ISSUE THREAD

**Issue by MikhailKlemin** [tebeka/selenium#99]
does it works? 
I trying to get a page source, but getting nil

		elem, err := wd.FindElement(selenium.ByXPATH, "/html")
		if err != nil {
			log.Println(err)
		}
		fmt.Println(elem.TagName()) //Prints html,nil as expected
		body, err := elem.GetAttribute("innerHTML")
		if err != nil {
			log.Println(err) // logs error nil response
		}

while `elem.Text()` works fine

well I just used javascript for this, but still wonder

	sI, err := wd.ExecuteScript("return document.documentElement.innerHTML", []interface{}{})
		if err != nil {
			log.Println(err)
		}

**Comment by minusnine** [comment]
`GetAttribute` returns the value of an HTML attribute. `innerHTML` is a DOM property.

**Comment by MikhailKlemin** [comment]
Well, It used to work before. As it works with Python, Java, C# ... 
So there are no way to get HTML of an Web Element?

**Comment by zarte** [comment]
you can by the way:    
  
htmlelem,_ := wd.FindElement(selenium.ByTagName, "html")  
 html, err := htmlelem.GetAttribute("outerHTML")  //or  htmlelem.GetAttribute("innerHTML")
